<?php

namespace KTSport\WebBundle\Entity;

use Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository;

/**
 * ButtonsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ButtonsRepository extends EntityRepository
{
	public function buttonsNavegacion() { 
    	return $this->createQueryBuilder('button')
    			->where('button.id != 40 and button.id != 41 and button.bar = 1')
				->getQuery()
				->getResult();
	}

	/**
     * Find buttons where url like 'kt_sport_web'.
     *
     * @return Collection
     */
    public function findUrls()
    {
        return $this->createQueryBuilder('button')
                ->where("button.url LIKE 'kt_sport_web%'")
                ->getQuery()
                ->getResult();
    }
}
