<?php

namespace KTSport\WebBundle\Entity;

use Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository;

/**
 * DealersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DealersRepository extends EntityRepository
{
	public function findDealers() { 
    return $this->createQueryBuilder('dealer')
    			->addOrderBy('dealer.id', 'desc')
				->getQuery()
				->getResult();
	}
}
