<?php

namespace KTSport\WebBundle\Entity;

use Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository;

/**
 * EventsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventsRepository extends EntityRepository
{
	public function findAllOrderedByDate() { 
    return $this->createQueryBuilder('event')
				->addOrderBy('event.date', 'desc')
				->getQuery()
				->getResult();
	} 
}
