<?php

namespace KTSport\WebBundle\Entity;

use Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository;

/**
 * SubButtonsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubButtonsRepository extends EntityRepository
{
	/**
     * Find subbuttons where url like 'kt_sport_web'.
     *
     * @return Collection
     */
    public function findUrls()
    {
        return $this->createQueryBuilder('subbutton')
                ->where("subbutton.url LIKE 'kt_sport_web%'")
                ->getQuery()
                ->getResult();
    }
}
