<?php

namespace KTSport\WebBundle\Entity;

use Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository;

/**
 * SubButtonsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubButtonsRepository extends EntityRepository
{
	/**
     * Find subbuttons where url like 'kt_sport_web'.
     *
     * @return Collection
     */
    public function findUrls()
    {
        return $this->createQueryBuilder('subbutton')
                ->where("subbutton.url LIKE 'kt_sport_web%'")
                ->getQuery()
                ->getResult();
    }

    /**
     * Create filter paginator.
     *
     * @param array $criteria
     * @param array $sorting
     *
     * @return PagerfantaInterface
     */
    public function createFilterPaginator($criteria = array(), $sorting = array())
    {
        $queryBuilder = parent::getCollectionQueryBuilder()
            ->select('subbutton')
        ;

        if (!empty($criteria['title'])) {
            $queryBuilder
                ->andWhere('subbutton.title LIKE :title')
                ->setParameter('title', '%'.$criteria['title'].'%')
            ;
        }
        if (!empty($criteria['content'])) {
            $queryBuilder
                ->andWhere('subbutton.content LIKE :content')
                ->setParameter('content', '%'.$criteria['content'].'%')
            ;
        }

        if (empty($sorting)) {
            if (!is_array($sorting)) {
                $sorting = array();
            }
            $sorting['title'] = 'desc';
        }

        $this->applySorting($queryBuilder, $sorting);

        return $this->getPaginator($queryBuilder);
    }

    /**
     * {@inheritdoc}
     */
    protected function getAlias()
    {
        return 'subbutton';
    }
}
