##
# KTSport
##
ktsport_index:
    pattern:  /
    defaults: { _controller: sylius.controller.frontend.homepage:indexAction }

ktsport_instructions:
    pattern:  /instructions
    defaults: { _controller: sylius.controller.frontend.homepage:instructionsAction }

ktsport_products:
    pattern:  /product/{section}
    defaults: { _controller: sylius.controller.frontend.homepage:productsAction, section: 'products' }

ktsport_original:
    pattern:  /original/{section}
    defaults: { _controller: sylius.controller.frontend.homepage:originalAction, section: 'products' }

ktsport_what_is_kt_tape:
    pattern:  /what-is-kt-tape
    defaults: { _controller: sylius.controller.frontend.homepage:what_is_kt_tapeAction }

ktsport_where_to_buy:
    pattern:  /where-to-buy
    defaults: { _controller: sylius.controller.frontend.homepage:wheretobuyAction }

ktsport_clinical:
    pattern:  /clinical
    defaults: { _controller: sylius.controller.frontend.homepage:clinicalAction }

ktsport_events:
    pattern:  /events
    defaults: { _controller: sylius.controller.frontend.homepage:eventsAction }

ktsport_videos:
    pattern:  /videos/{id}
    defaults: { _controller: sylius.controller.frontend.homepage:videosAction, id: 10000 }

ktsport_dealers:
    pattern:  /dealers
    defaults: { _controller: sylius.controller.frontend.homepage:dealersAction }

ktsport_contact:
    pattern:  /contact
    defaults: { _controller: sylius.controller.frontend.homepage:contactAction }

ktsport_aboutus:
    pattern:  /about-us
    defaults: { _controller: sylius.controller.frontend.homepage:aboutusAction }

ktsport_pdf:
    pattern:  /pdf
    defaults: { _controller: sylius.controller.frontend.homepage:pdfAction }

ktsport_shop:
    resource: @SyliusWebBundle/Resources/config/routing/frontend/shop/main.yml
    prefix: /shop

ktsport_disclaimer:
    pattern:  /disclaimer
    defaults:
        _controller: FrameworkBundle:Template:template
        template: SyliusWebBundle:Frontend/Homepage:disclaimer.html.twig