##
# Actividad
##
sylius_backend_actividad_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: sylius.controller.actividad:indexAction
        _sylius:
            template: SyliusWebBundle:Backend/Actividad:index.html.twig

sylius_backend_actividad_create:
    pattern: /new
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.actividad:createAction
        _sylius:
            template: SyliusWebBundle:Backend/Actividad:create.html.twig
            redirect: sylius_backend_actividad_show

sylius_backend_actividad_update:
    pattern: /{id}/edit
    methods: [GET, PUT]
    defaults:
        _controller: sylius.controller.actividad:updateAction
        _sylius:
            template: SyliusWebBundle:Backend/Actividad:update.html.twig
            redirect: sylius_backend_actividad_show

sylius_backend_actividad_delete:
    pattern: /{id}
    methods: [DELETE]
    defaults:
        _controller: sylius.controller.actividad:deleteAction
        _sylius:
            template: SyliusWebBundle:Backend/Misc:delete.html.twig
            redirect: sylius_backend_actividad_index

sylius_backend_actividad_show:
    pattern: /{id}
    methods: [GET]
    defaults:
        _controller: sylius.controller.actividad:showAction
        _sylius:
            template: SyliusWebBundle:Backend/Actividad:show.html.twig